#:schema node_modules/wrangler/config-schema.json
name = "toolskita"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
NODE_VERSION = "22"
BUN_VERSION = "0"
NPM_FLAGS = "--version"

[build]
command = "npm install && npm run build"
